### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by chhil** [vietj/advanced-vertx-guide#10]
Attempting to build as referenced output text is not dereferenced on the webpage.

A snippet just before failure.
> [INFO] --- asciidoctor-maven-plugin:1.5.3:process-asciidoc (default) @ vertx-material ---
> io/console not supported; tty will not be manipulated
> Jul 30, 2018 4:28:02 PM org.asciidoctor.internal.JRubyAsciidoctor renderFile
> SEVERE: (ArgumentError) invalid byte sequence in UTF-8
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 8.857 s
> [INFO] Finished at: 2018-07-30T16:28:02+05:30
> [INFO] Final Memory: 32M/577M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (default) on project vertx-material: Execution default of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: org.jruby.exceptions.RaiseException: (ArgumentError) invalid byte sequence in UTF-8 -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by vietj** [comment]
can you give a try again ?
