### ISSUE TITLE
Java source code blocks of Integrating Netty Chapter are not displayed

### ISSUE THREAD

**Issue by NilsRenaud** [vietj/advanced-vertx-guide#13]
### Context

The Java source code in https://github.com/vert-x3/advanced-vertx-guide/blob/master/src/main/asciidoc/Integrating_Netty.adoc is not displayed though the sources exist in the repository.

**Comment by vietj** [comment]
yes that is expected, you can have at the online version https://vert-x3.github.io/advanced-vertx-guide/index.html
