### ISSUE TITLE
Example code no longer displays

### ISSUE THREAD

**Issue by aschrijver** [vietj/advanced-vertx-guide#4]
In https://github.com/vietj/vertx-materials/blob/master/src/main/asciidoc/Demystifying_the_event_loop.adoc the code examples are broken. 
The text results are not dereferenced it seems.

**Comment by rdruss** [comment]
If you build the docs then the relevant examples are inserted into the generated book.html.

![examples](https://user-images.githubusercontent.com/367748/27719896-d3727424-5d12-11e7-97cb-9ae0851728de.png)

**Comment by vietj** [comment]
thanks Rodney
