### ISSUE TITLE
This is project is a valuable resource, but where is is published?

### ISSUE THREAD

**Issue by mslinn** [vietj/advanced-vertx-guide#8]
Where is the published document [for this source](https://github.com/vietj/vertx-materials/blob/master/src/main/asciidoc/Demystifying_the_event_loop.adoc)?

**Comment by vietj** [comment]
here https://github.com/vietj/vertx-materials/blob/master/src/main/asciidoc/output/book.adoc

**Comment by mslinn** [comment]
Excellent, thank you. Why not put that link in the README so others can find it easily?

**Comment by mslinn** [comment]
Some additional information would be helpful to understand the information presented. Questions that arise for me are:

1. IO threads are mentioned without describing them, which confused me. Does this means that the threads for IO are managed by a dedicated thread pool? If so, what other thread pools does Vert.x use? 

1. I found [this document on cubrid.org](https://www.cubrid.org/blog/understanding-vertx-architecture-part-2), which might help answer that question and others. There is a section entitled **Vert.x Thread Pool**, which states that the `Acceptor` thread pool is for socket connections (one thread is created for each port). Is this the IO thread pool that I expect to find? 

    Paraphrasing [this StackOverflow thread](https://stackoverflow.com/a/40747109/553865): The Vert.x event loop is multithreaded and handles Netty socket IO events for connections and requests. *Did I paraphrase this correctly?*

1. Your document says that multiple event loop instances are normally created, in fact twice the number of available cores, each with its own worker thread. This is a [parallelization factor](http://pro.arcgis.com/en/pro-app/tool-reference/environment-settings/parallel-processing-factor.htm) of 50%. The `cubrid.org` document differs from what you say in your document; that document says the number of event loop instances created by default equals the number of CPUs. Which document is correct?

1. How is communication between an event loop context and worker contexts implemented? From the description it seems likely that the communication mechanism needs to be threadsafe for some scenarios.

    One way to implement a threadsafe communication mechanism might be to use a concurrent queue. On the JVM this usually means a [java.util.concurrent.BlockingQueue](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/BlockingQueue.html) implementation  such as a [LinkedBlockingQueue](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/LinkedBlockingQueue.html). If a `java.util.concurrent` data structure or something equivalent is not used, then the communications between the contexts is unlikely to be threadsafe. [The Vert.x JavaDoc suggests](http://vertx.io/docs/apidocs/io/vertx/core/VertxOptions.html#DEFAULT_INTERNAL_BLOCKING_POOL_SIZE) that a blocking queue is in fact used for at least some scenarios. A table describing when threadsafe communication is implemented would help.

1. I am considering a scenario where multiple users and server processes need to evaluate JavaScript code. Either all would share the same JavaScript process, or each user and server process would have its own JavaScript evaluator, initialized to the same state. I am unclear how to configure Vert.x such that a single user would connect to their own JavaScript evaluator. Every user would need to have an associated evaluator (a 'sticky' evaluator during the lifetime of a use session). For some use cases it might be desirable to have only one evaluator, and put a concurrent queue in front of it. Again, does Vert.x already uses concurrent queues for workers? 

I am currently reading [this document](http://escoffier.me/vertx-hol/) to see if it answers any of the above questions. Seems like the request / reply paradigm is what I might want for the shared JavaScript evaluator.

**Comment by vietj** [comment]
would you mind to try to contribute to the document ?

I would really make this doc move forward and become a kind of live mini book

**Comment by mslinn** [comment]
I would be happy to continue this dialog with you, and contribute as my understanding grows. Gitbooks are really good for this. [Here is a gitbook](https://mslinn.gitbooks.io/sbt-ethereum/content/) that I am working on with another person.

**Comment by vietj** [comment]
here http://www.julienviet.com/advanced-vertx-guide/
